
---
- hosts: all
  become: yes
  connection: ssh

  tasks:
    - name: creating a file with ansible playbook
      file:
        path: /tmp/userfile
        state: file

    - name: creating a dir
      file:
        path: /tmp/dir1
        state: directory

