---
- hosts: all
  become: yes
  user: ansible
  connection: ssh

  tasks:
    - name: installing java software
      yum:  
        name: java 
        state: present
      when: ansible_os_family == "RedHat"

    - name: installing java  software for debian
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian" 

    - name: download tomcat pkg
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.82/bin/apache-tomcat-8.5.82.tar.gz
        dest: /opt

    - name: extract tomcat s/w
      unarchive:
        src: /opt/apache-tomcat-8.5.82.tar.gz
        dest: /opt
        remote_src: yes

    - name: provide executable permissions
      file:
        path: /opt/apache-tomcat-8.5.82/bin/startup.sh
        mode: 0777
     
    - name: start tomcat servica
      shell: nohup ./startup.sh
      args: 
        chdir: /opt/apache-tomcat-8.5.82/bin    
            
