---
- hosts: all
  become: yes
  connection: ssh
  user: ansible

  tasks:
    - name: installing httpd package
      yum:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: starting httpd service
      service:
        name: httpd
        state: started
      when: ansible_os_family == "RedHat"

    - name: installing apache2 s/w
      apt: 
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: starting apache2 pkg
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

    - name: copying a file
      copy:
        src: /home/ansible/index.html
        dest: /var/www/html
        owner: system1
        mode: 0777
