---
- hosts: all
  become: yes

  tasks:
    - name: installing pkg
      yum:
        name: httpd
        state: present
    - name: starting the service
      service:
        name: httpd
        state: started

